version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=micro
      - MYSQL_PASSWORD=root
  back:
    image: chaffariinfo/backendapp:3
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=micro
      - DATABASE_PORT=3306
    ports:
      - 8085:8085
  front:
    image: chaffariinfo/frontendapp
    ports:
      - 9000:80
